---
    - name: instalar MariaDB
      apt:
        name:
          - mariadb-server
          - python3-pymysql
          - python3-mysqldb
          - python-pymysql
          - python-mysqldb
        state: latest
  
    - name: Iniciar MariaDB
      service:
        name: mariadb
        enabled: true
        state: started

#    - name: Establecer contraseña para usuario root
 #     shell: mysql -u root --password=toor -e "select(1);"

    - name: update mysql root password for all root accounts  
      mysql_user:  
        name: root  
        #         host: localhost
        password: "{{ mysql_root_password }}"  
        login_user: root  
        login_password: "{{ mysql_root_password }}"  
        check_implicit_admin: yes  
        priv: "*.*:ALL,GRANT"  
      with_items:  
      - "{{ ansible_hostname }}"  
      - 127.0.0.1  
      - ::1  
      - localhost

    - name: Crear base de datos para WordPress
      mysql_db:
        name: wordpress_db
        login_user: root
        login_password: toor
        login_host: localhost
        state: present

    - name: Crear usuario para la base de datos
      mysql_user:
        state: present
        name: wpuser
        password: Passw0rd!
        priv: 'wordpress_db.*:ALL,GRANT'
