---
    - name: instalar MariaDB
      apt:
        name:
          - mariadb-server
          - python3-pymysql
          - python3-mysqldb
          - python-pymysql
          - python-mysqldb
        state: latest
  
    - name: Iniciar MariaDB
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Establecer contraseña para usuario root
      shell: mysql -u root --password=toor -e "select(1);"
      
    - name: Collect all possible information using passwordless root access
      mysql_info:
        login_user: root
      register: mysqlinfo

    - name: Print mysqlinfo
      debug:
        msg: "{{ mysqlinfo }}"

    - name: Crear base de datos para WordPress
      mysql_db:
        name: wordpress_db
        login_user: root
        login_password: toor
        login_host: localhost
        state: present

    - name: Crear usuario para la base de datos
      mysql_user:
        state: present
        name: wpuser
        password: Passw0rd!
        priv: 'wordpress_db.*:ALL,GRANT'
