---
    - name: instalar MariaDB
      apt:
        name:
          - mariadb-server
          - python3-pymysql
          - python3-mysqldb
          - python-pymysql
          - python-mysqldb
        state: latest
  
    - name: Iniciar MariaDB
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Establecer contraseña para usuario root
      shell: mysql -u root --password=toor -e "select(1);"

    - name: Dar todos los permisos al usuario root
      shell: mysql -u root --password=toor -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'new_password' WITH GRANT OPTION;"

    - name: Crear base de datos para WordPress
      mysql_db:
        name: wordpress_db
        #login_user: root
        #login_password: toor
        #login_host: localhost
        state: present

    - name: crear usuario
      mysql_user: name=fran password=fran1234 state=present privs="wordpress_db.*:ALL"

    - name: Crear usuario para la base de datos
      mysql_user:
        state: present
        name: wpuser
        password: Passw0rd!
        priv: 'wordpress_db.*:ALL,GRANT'
