---
    - name: "Actualizar paquetes"
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Upgradear paquetes"
      apt:
        upgrade: dist

    - name: "Instalar nginx"
      apt:
        name:
          - nginx
        state: present

    - name: "Instalar paquetes necesarios"
      apt:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysql
          - php-json
          - php-opcache
          - php-mbstring
          - php-xml
          - php-gd
          - php-curl
        state: present
