---
    - name: "Actualizar paquetes"
      yum:
        update_cache: yes

    - name: "Upgradear paquetes"
      yum:
        name: "*"
        state: latest

    - name: "Instalar nginx"
      yum:
        name:
          - nginx
        state: present

    - name: "Instalar paquetes necesarios"
      yum:
        name:
          - php
          - php-cli
          - php-fpm
            #          - php-mysql
          - php-json
          - php-opcache
          - php-mbstring
          - php-xml
          - php-gd
          - php-curl
        state: present
