---
- name: "Wordpress+Nginx+MariaDB"
  hosts: all
  become: yes
  roles:
     - role: Debian-nginx
       when: ansible_os_family == "Debian"

     - role: RedHat-nginx
       when: ansible_os_family == "RedHat"

     - role: wordpress

     - role: Debian-mariadb
       when: ansible_os_family == "Debian"

     - role: RedHat-mariadb
       when: ansible_os_family == "RedHat"