---
    - name: "Crear directorio"
      file:
        path: /var/www/html/wordpress/public_html
        state: directory

    - name: "Crear directorio sites-available"
      file:
        path: /etc/nginx/sites-available/
        state: directory

    - name: "Copiar archivo de configuración"
      copy:
        src: wordpress.conf
        dest: /etc/nginx/sites-available/

    - name: "Crear directorio sites-enabled"
      file:
        path: /etc/nginx/sites-enabled/
        state: directory

    - name: "Crear enlace simbolico"
      file:
        src: /etc/nginx/sites-available/wordpress.conf
        dest: /etc/nginx/sites-enabled/wordpress.conf
        state: link
      ignore_errors: true

    - name: "Eliminar fichero default"
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      ignore_errors: true

    - name: "Descargar Wordpress"
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/wordpress/public_html/
        mode: "777"

    - name: "Extraer ficheros"
      unarchive:
        src: /var/www/html/wordpress/public_html/wordpress-6.1.1.tar.gz
        dest: /var/www/html/wordpress/public_html/
        remote_src: True

    - name: "Sacar ficheros de la carpeta Wordpress"
      copy:
        src: /var/www/html/wordpress/public_html/wordpress/
        dest: /var/www/html/wordpress/public_html/
        remote_src: True

    - name: "Eliminar carpeta Wordpress"
      file:
        path: /var/www/html/wordpress/public_html/wordpress
        state: absent

    - name: "Crear grupo www-data"
      group:
        name: "www-data"
        state: present

    - name: "Crear usuario www-data"
      user:
        name: "www-data"
        group: "www-data"
        state: present

    - name: "Cambiar propietario y permisos"
      file:
        path: /var/www/html/wordpress/public_html/
        owner: www-data
        group: www-data
        mode: "755"
        recurse: true

    - name: "Cambiar nomre de fichero"
      command: mv /var/www/html/wordpress/public_html/wp-config-sample.php /var/www/html/wordpress/public_html/wp-config.php

    - name: "Copiar fichero de configuración de Wordpress"
      copy:
        src: wp-config.php
        dest: /var/www/html/wordpress/public_html

    - name: "Reiniciar Nginx"
      service:
        name: nginx
        enabled: true
        state: restarted
